saiij/editable-web-quiz

- js/quiz.js
this fixes the issue and enables the functionality you have requested in the issue
> fixing issue #3 "timer fix"

- js/demo.js
Add 4 demo questions to demo.js
> Add demo questions

- js/demo.js
The JS file was invalid due to a missing "
on line 59, right after the question
> Fix a missing "

- js/demo.js
Add 4 additional sample questions
> Add More sample questions

- js/demo.js
> [ADD] question about name of planet after earth

- js/demo.js
Added two questions to the list and also fixed the syntax error.
Fixes #7
> Praveen add more questions

- js/demo.js
> Fixed the syntax error.

- js/demo.js
> Fixed all the syntax errors.

- js/demo.js
Check out the techie questions @saiij
> Added some more questions

- README.md
> Added link to Contribution.

- CONTRIBUTING.md
- src/js/demo.js
> added categories

- README.md
- src/js/demo.js
more questions added to the quiz
> more questions added to the quiz

- README.md
- src/js/demo.js
Added a question about the first female Prime Minister of Europe and added my name to the contributors sections of the README.md file!
> More questions

- src/js/demo.js
Added the question of: "Who created React.js?"
> Added a question

- IMPROVEMENTS.md
> Improvements suggested

- IMPROVEMENTS.md
> Added Suggestions

- IMPROVEMENTS.md
template for uploading custom questions and a way to show high score/quick response times for the user
> Added two suggestions to improve the game 

- IMPROVEMENTS.md
Hey,
I played your quiz a few times and added some Feedback, I hope it helps your project! :)
> added Feedback

- src/js/demo.js
Added four questions about space and science and fixed some comma errors
> Space questions

- src/js/demo.js
> added 2 questions

- src/js/demo.js
Added 4 more questions to the quiz. Couple easy, and one for science.
Enjoy!
References #7
> New questions for quiz.
